sudo: false
language: node_js
node_js:
- 6.7.0

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: test
      script: npm test
      script: npm test
      script: node --version
    - stage: repeat test
      script: npm test
